Repository mash-up-kr/YourName-iOS, pull requests merged in 2021-09, with the labels that each got.

#4 [Feature] Network layer
  YourName/Podfile
  YourName/Podfile.lock
  YourName/YourName.xcodeproj/project.pbxproj
  YourName/YourName/Sources/App/AppDelegate.swift
  YourName/YourName/Sources/App/main.swift
  YourName/YourName/Sources/Common/Rx+/ObserverType+.swift
  YourName/YourName/Sources/Common/ViewController.swift
  YourName/YourName/Sources/Data Layer/Network/Extensions/Foundation+Decoder.swift
  YourName/YourName/Sources/Data Layer/Network/Extensions/Foundation+Network.swift
  YourName/YourName/Sources/Data Layer/Network/HTTP/HTTP.swift
  YourName/YourName/Sources/Data Layer/Network/HTTP/HTTPError.swift
  YourName/YourName/Sources/Data Layer/Network/HTTPClient.swift
  YourName/YourName/Sources/Data Layer/Network/Network.swift
  YourName/YourName/Sources/Data Layer/Network/NoContent.swift
  YourName/YourName/Sources/Data Layer/Network/Protocols/API.swift
  YourName/YourName/Sources/Data Layer/Network/Protocols/Connectable.swift
  YourName/YourName/Sources/Data Layer/Network/Protocols/DataLoading.swift
  YourName/YourName/Sources/Data Layer/Network/Protocols/DataTask.swift
  YourName/YourName/Sources/Data Layer/Network/Protocols/Decoder.swift
  YourName/YourName/Sources/Data Layer/Network/Protocols/Networking.swift
  YourName/YourName/Sources/Data Layer/Network/Protocols/URLRequestConvertible.swift
  YourName/YourName/Sources/Enviroment/Enviorment.swift
  YourName/YourNameTests/NetworkTests/HTTPClientTests.swift
  YourName/YourNameTests/NetworkTests/NetworkTests.swift
  YourName/YourNameTests/NetworkTests/Test Doubles/FakeData.swift
  YourName/YourNameTests/NetworkTests/Test Doubles/MockAPI.swift
  YourName/YourNameTests/NetworkTests/Test Doubles/MockDataLoader.swift
  YourName/YourNameTests/NetworkTests/Test Doubles/MockDataTask.swift
  YourName/YourNameTests/NetworkTests/Test Doubles/MockDecodingService.swift
  YourName/YourNameTests/NetworkTests/Test Doubles/MockError.swift
  YourName/YourNameTests/NetworkTests/Test Doubles/MockNetwork.swift
  YourName/YourNameTests/NetworkTests/Test Doubles/MockSession.swift
  YourName/YourNameTests/NetworkTests/Test Doubles/TestResponse.swift
  YourName/YourNameUITests/Info.plist
  YourName/YourNameUITests/YourNameUITests.swift
Labels: feature

#6 [Feature] FLEX, ViewController Template 구현
  YourName/Podfile
  YourName/Podfile.lock
  YourName/YourName.xcodeproj/project.pbxproj
  YourName/YourName/Sources/Common/Extensions/Rx/ObserverType+.swift
  YourName/YourName/Sources/Common/Extensions/UIStackView+.swift
  YourName/YourName/Sources/Common/Extensions/UIView+.swift
  YourName/YourName/Sources/Common/Extensions/ViewController.swift
  YourName/YourName/Sources/Common/ViewController.swift
Labels: feature

#13 :bug: 초기 layout 설정 메서드 호출 시점 변경
  YourName/YourName/Sources/Common/Extensions/ViewController.swift
Labels: bug

#12 :sparkles: QRGenerator 구현
  YourName/YourName.xcodeproj/project.pbxproj
  YourName/YourName/Sources/Domain Layer/QR/QRGenerater.swift
Labels: feature

#10 View <-> Image 변환기 구현
  YourName/YourName.xcodeproj/project.pbxproj
  YourName/YourName/Sources/Domain Layer/Snapshot/SnapshotService.swift
Labels: feature

#7 [Feature] OAuth Interface 구현
  YourName/YourName.xcodeproj/project.pbxproj
  YourName/YourName/Sources/Domain Layer/Auth/Auth.swift
  YourName/YourName/Sources/Domain Layer/Auth/AuthResponse.swift
Labels: interface

#18 Feature/app initialization flow
  YourName/Podfile
  YourName/Podfile.lock
  YourName/YourName.xcodeproj/project.pbxproj
  YourName/YourName.xcodeproj/xcshareddata/xcschemes/YourName.xcscheme
  YourName/YourName/Sources/App/AppDelegate.swift
  YourName/YourName/Sources/Common/Extensions/String+.swift
  YourName/YourName/Sources/Common/Extensions/ViewController.swift
  YourName/YourName/Sources/Domain Layer/Auth/AccessTokenRepository.swift
  YourName/YourName/Sources/Domain Layer/Auth/AuthenticationDelegate.swift
  YourName/YourName/Sources/Domain Layer/Auth/FakeAccessTokenRepository.swift
  YourName/YourName/Sources/UI Layer/DIContainer/Root/RootDependencyContainer.swift
  YourName/YourName/Sources/UI Layer/DIContainer/Root/SignedIn/SignedInDependencyContainer.swift
  YourName/YourName/Sources/UI Layer/DIContainer/Root/SignedOut/SignedOutDependencyContainer.swift
  YourName/YourName/Sources/UI Layer/Navigation.swift
  YourName/YourName/Sources/UI Layer/Screens/CardBook/CardBookViewController.swift
  YourName/YourName/Sources/UI Layer/Screens/Home/HomeTabBarController.swift
  YourName/YourName/Sources/UI Layer/Screens/Home/HomeViewModel.swift
  YourName/YourName/Sources/UI Layer/Screens/Home/Tab.swift
  YourName/YourName/Sources/UI Layer/Screens/MyCardList/MyCardListViewController.swift
  YourName/YourName/Sources/UI Layer/Screens/Profile/ProfileViewController.swift
  YourName/YourName/Sources/UI Layer/Screens/Quest/QuestViewController.swift
  YourName/YourName/Sources/UI Layer/Screens/Root/RootViewController.swift
  YourName/YourName/Sources/UI Layer/Screens/Root/RootViewModel.swift
  YourName/YourName/Sources/UI Layer/Screens/Root/ViewControllers/RootViewController.swift
  YourName/YourName/Sources/UI Layer/Screens/Root/ViewModels/RootViewModel.swift
  YourName/YourName/Sources/UI Layer/Screens/SignIn/SignInViewController.swift
  YourName/YourName/Sources/UI Layer/Screens/SignIn/SignInViewModel.swift
  YourName/YourName/Sources/UI Layer/Screens/Splash/SplashViewController.swift
  YourName/YourName/Sources/UI Layer/Screens/Splash/SplashViewModel.swift
  YourName/YourNameTests/RootTests/RootViewModelTests.swift
  YourName/YourNameTests/SplashTests/MockAuthenticationDelegate.swift
  YourName/YourNameTests/SplashTests/SplashViewModelTests.swift
Labels: 🧪 test code, 🤖 prototype

#17 Feature/card detail entrance flow - ⚠️ app initialization 이 선행 병합 되어야합니다
  YourName/YourName.xcodeproj/project.pbxproj
  YourName/YourName/Sources/Common/Extensions/Array+.swift
  YourName/YourName/Sources/Domain Layer/Auth/FakeAccessTokenRepository.swift
  YourName/YourName/Sources/Domain Layer/MyCard/Card.swift
  YourName/YourName/Sources/Domain Layer/MyCard/MockMyCardRepository.swift
  YourName/YourName/Sources/Domain Layer/MyCard/MyCardRepository.swift
  YourName/YourName/Sources/UI Layer/Navigation.swift
  YourName/YourName/Sources/UI Layer/Screens/CardDetail/CardDetailDependencyContainer.swift
  YourName/YourName/Sources/UI Layer/Screens/CardDetail/CardDetailViewController.swift
  YourName/YourName/Sources/UI Layer/Screens/CardDetail/CardDetailViewModel.swift
  YourName/YourName/Sources/UI Layer/Screens/Home/SignedInDependencyContainer.swift
  YourName/YourName/Sources/UI Layer/Screens/MyCardList/MyCardListDependencyContainer.swift
  YourName/YourName/Sources/UI Layer/Screens/MyCardList/MyCardListViewController.swift
  YourName/YourName/Sources/UI Layer/Screens/MyCardList/MyCardListViewModel.swift
  YourName/YourName/Sources/UI Layer/Screens/Root/RootDependencyContainer.swift
  YourName/YourName/Sources/UI Layer/Screens/Root/RootViewController.swift
  YourName/YourName/Sources/UI Layer/Screens/Root/RootViewModel.swift
  YourName/YourName/Sources/UI Layer/Screens/SignIn/SignedOutDependencyContainer.swift
  YourName/YourNameTests/MyCardListTests/MyCardListViewModelTests.swift
  YourName/YourNameTests/NetworkTests/HTTPClientTests.swift
  YourName/YourNameTests/NetworkTests/NetworkTests.swift
  YourName/YourNameTests/RootTests/RootViewModelTests.swift
  YourName/YourNameTests/SplashTests/SplashViewModelTests.swift
  YourName/YourNameTests/SplashTests/Test Doubles/MockAuthenticationDelegate.swift
Labels: 🐛 bug, ☠️ do not merge, 🧪 test code, 🤖 prototype

#21 :bug: Root 네비게이션 오류 수정
  YourName/YourName.xcodeproj/project.pbxproj
  YourName/YourName/Sources/UI Layer/Screens/CardBook/CardBookViewController.swift
  YourName/YourName/Sources/UI Layer/Screens/Home/HomeTab.swift
  YourName/YourName/Sources/UI Layer/Screens/Home/HomeTabBarController.swift
  YourName/YourName/Sources/UI Layer/Screens/Home/HomeViewModel.swift
  YourName/YourName/Sources/UI Layer/Screens/Home/SignedInDependencyContainer.swift
  YourName/YourName/Sources/UI Layer/Screens/MyCardList/MyCardListViewController.swift
  YourName/YourName/Sources/UI Layer/Screens/Profile/ProfileViewController.swift
  YourName/YourName/Sources/UI Layer/Screens/Quest/QuestViewController.swift
  YourName/YourName/Sources/UI Layer/Screens/Root/RootViewController.swift
  YourName/YourName/Sources/UI Layer/Screens/Splash/SplashViewController.swift
  YourName/YourNameTests/SplashTests/SplashViewModelTests.swift
Labels: 🐛 bug
